/* global window */

// Catalogue data-driven (min 15 armes). Comportements implémentés dans app.js via behaviorId.

window.SOPOR_WEAPONS = [
  {
    id: "sword_neon",
    name: "Épée néon",
    type: "melee",
    behaviorId: "melee_arc",
    rarity: "common",
    essenceCost: 0.8,
    cooldownMs: 260,
    damage: 8,
    reach: 34,
    arcDeg: 100,
    knockback: 120,
  },
  {
    id: "dagger_glitch",
    name: "Dague glitch",
    type: "melee",
    behaviorId: "melee_arc",
    rarity: "common",
    essenceCost: 0.55,
    cooldownMs: 170,
    damage: 5,
    reach: 26,
    arcDeg: 80,
    knockback: 90,
  },
  {
    id: "axe_root",
    name: "Hache des Racines",
    type: "melee",
    behaviorId: "melee_arc",
    rarity: "uncommon",
    essenceCost: 1.15,
    cooldownMs: 380,
    damage: 12,
    reach: 36,
    arcDeg: 110,
    knockback: 160,
  },
  {
    id: "mace_pulse",
    name: "Masse à Impulsion",
    type: "melee",
    behaviorId: "melee_slam",
    rarity: "uncommon",
    essenceCost: 1.5,
    cooldownMs: 520,
    damage: 16,
    radius: 44,
    knockback: 190,
  },
  {
    id: "spear_lumen",
    name: "Lance Lumen",
    type: "melee",
    behaviorId: "melee_thrust",
    rarity: "common",
    essenceCost: 0.95,
    cooldownMs: 300,
    damage: 9,
    reach: 56,
    knockback: 120,
  },
  {
    id: "scythe_reaper",
    name: "Faux du Souvenir",
    type: "melee",
    behaviorId: "melee_arc",
    rarity: "rare",
    essenceCost: 1.4,
    cooldownMs: 420,
    damage: 14,
    reach: 52,
    arcDeg: 150,
    knockback: 170,
  },
  {
    id: "pitchfork_garden",
    name: "Fourche du Jardin",
    type: "melee",
    behaviorId: "melee_thrust",
    rarity: "common",
    essenceCost: 0.75,
    cooldownMs: 240,
    damage: 7,
    reach: 58,
    knockback: 105,
  },
  {
    id: "bow_arc",
    name: "Arc d'Arcadie",
    type: "projectile",
    behaviorId: "projectile_arrow",
    rarity: "common",
    essenceCost: 0.6,
    cooldownMs: 280,
    damage: 7,
    projectile: { speed: 360, ttlMs: 950, spreadDeg: 2, pierce: 0 },
  },
  {
    id: "crossbow_forge",
    name: "Arbalète de Forge",
    type: "projectile",
    behaviorId: "projectile_bolt",
    rarity: "uncommon",
    essenceCost: 0.9,
    cooldownMs: 420,
    damage: 12,
    projectile: { speed: 520, ttlMs: 900, spreadDeg: 1, pierce: 1 },
  },
  {
    id: "slingshot_pocket",
    name: "Lance-pierre de Poche",
    type: "projectile",
    behaviorId: "projectile_pebble",
    rarity: "common",
    essenceCost: 0.25,
    cooldownMs: 140,
    damage: 3,
    projectile: { speed: 460, ttlMs: 700, spreadDeg: 5, pierce: 0 },
  },
  {
    id: "wand_mnemosyne",
    name: "Baguette Mnémosyne",
    type: "projectile",
    behaviorId: "projectile_orb",
    rarity: "uncommon",
    essenceCost: 1.0,
    cooldownMs: 320,
    damage: 9,
    projectile: { speed: 320, ttlMs: 1200, spreadDeg: 0, pierce: 0 },
  },
  {
    id: "grimoire_flicker",
    name: "Grimoire Scintillant",
    type: "hybrid",
    behaviorId: "hybrid_arc_orb",
    rarity: "rare",
    essenceCost: 1.25,
    cooldownMs: 360,
    damage: 10,
    reach: 30,
    arcDeg: 95,
    projectile: { speed: 300, ttlMs: 1150, spreadDeg: 0, pierce: 0 },
  },
  {
    id: "chakram_loop",
    name: "Chakram Boucleur",
    type: "projectile",
    behaviorId: "projectile_boomerang",
    rarity: "rare",
    essenceCost: 1.1,
    cooldownMs: 520,
    damage: 11,
    projectile: { speed: 420, ttlMs: 900, spreadDeg: 0, pierce: 1 },
  },
  {
    id: "whip_vine",
    name: "Fouet de Veines",
    type: "melee",
    behaviorId: "melee_whip",
    rarity: "uncommon",
    essenceCost: 0.95,
    cooldownMs: 310,
    damage: 8,
    reach: 70,
    knockback: 140,
  },
  {
    id: "essence_cannon",
    name: "Canon à Essence",
    type: "projectile",
    behaviorId: "projectile_cannon",
    rarity: "epic",
    essenceCost: 2.2,
    cooldownMs: 900,
    damage: 24,
    projectile: { speed: 280, ttlMs: 1400, spreadDeg: 0, pierce: 2 },
  },
  {
    id: "needle_gun",
    name: "Pistolet à Aiguilles",
    type: "projectile",
    behaviorId: "projectile_burst",
    rarity: "rare",
    essenceCost: 1.2,
    cooldownMs: 560,
    damage: 6,
    burst: { count: 4, stepMs: 55 },
    projectile: { speed: 600, ttlMs: 650, spreadDeg: 6, pierce: 0 },
  },
];
